* Commentary: 

 - Bitcoin donations gratefully accepted :: 1FgnGFwRES9MGzoieRDWLmLkjqMT3AsjQF

This library provides some macros for extracting keyword args from lists.
It can be helpful in situations where normal cl-defun arglist handling is not enough.

* Macros

 - extract-keyword-arg : 
      Remove KEY & following item from list referenced by LSTSYM, and return item.
 - extract-keyword-bindings : 
      Extract KEYS and corresponding values from ARGS, and return in let-style bindings list.
 - extract-first-keyword-arg :
      Remove & return first key & following item from list referenced by LSTSYM.
 - loop-over-keyword-args :
      Loop over the keyword args in list LST, evaluating BODY forms each time.

* Installation

Put keyword-arg-macros.el in a directory in your load-path, e.g. ~/.emacs.d/
You can add a directory to your load-path with the following line in ~/.emacs
(add-to-list 'load-path (expand-file-name "~/elisp"))
where ~/elisp is the directory you want to add 
(you don't need to do this for ~/.emacs.d - it's added by default).

Add the following to your ~/.emacs startup file.

(require 'keyword-arg-macros)
